- hosts: webservers
  roles:
  - role: java
  - role: tomcat
    vars:
      install_dir: "/opt/tomcat"
      java: "{{ hostvars[inventory_hostname]['JAVA_HOME'] }}"
  - role: nginx
    vars:
      app_port: 8080
      tomcat_folder: "{{ hostvars[inventory_hostname]['TOMCAT'] }}"
  - role: app
    vars:
      install_dir: "{{ hostvars[inventory_hostname]['TOMCAT'] }}/webapps"

