- hosts: webservers
  vars:
    tomcat_dir: /opt/tomcat
    app_port: 8080

  roles:
    #- role: java
    #- role: nginx
  - role: tomcat
    vars:
      install_dir: "{{ tomcat_dir }}"
      java: "{{ hostvars[inventory_hostname]['JAVA_HOME'] }}"
  - role: app
    vars:
      install_dir: "{{ tomcat_dir }}/webapps"

